services:
  # The Node.js Backend Server
  - type: web
    name: escrow-crowd-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: "3005"
      - key: REDIS_URL
        fromDatabase:
          name: escrow-redis
          property: connectionString
      - key: SPONSOR_SECRET_KEY
        sync: false # You will set this in the Render dashboard or CLI
      - key: WHITELISTED_CONTRACTS
        value: CANOYAM53C5Q6DNECYVNIQAQN5VI4GMWRXPGQ6CDTHNZBWPBAJ3A7AYA,CARXQBPFKYA5ANRURAQV4LCPCEN2KJGRKZPXMOCXT4IVKYKL6QBJ3GLY
      
  # The Redis Instance for BullMQ
  - type: redis
    name: escrow-redis
    ipAllowList: [] # internal access only
    plan: free
